### ISSUE TITLE
Remove UI icons

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/manager.assets.ubuntu.com#76]
Please can we remove [this set of icons](https://manager.assets.ubuntu.com/?q=canonical-iconset-07&type=).

These were added before we finished the new UI icons, the finished set is now ready to be uploaded.

I'd like to get off to a good start with these, so we should avoid a duplicate set which may be used by mistake.

Thanks.

**Comment by nottrobin** [comment]
We had an email discussion about this, I'm not sure it came to a clear conclusion.

In general, deleting assets from the assets server is discouraged, to help prevent [link rot](https://en.wikipedia.org/wiki/Link_rot). Because of that, it's some work to achieve removing all these assets.

When [the assets server has been moved to k8s](https://github.com/canonical-web-and-design/master-epics/issues/18), we can then start to work on [the deprecation feature](https://github.com/canonical-web-and-design/assets.ubuntu.com/issues/98).

In the meantime, is it not sufficient to just change the tags? Either by adding "DEPRECATED", or remove the existing "canonical-iconset-07" tag? This way it will be clear to people finding those resources through the manager that they shouldn't be used any more, but leaves them there in case anyone has currently saved a link to them or in future wants to look at the evolution of our icons or whatever.

And then when the deprecation feature is developed they can be hidden from search etc.

**Comment by spencerbygraves** [comment]
@nottrobin thanks, I think that's fine. We'll use tags for now and wait for the deprecation feature. I'll close this.
